# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "fold": "00_core.ipynb",
         "A": "00_core.ipynb",
         "B": "00_core.ipynb",
         "Foo": "00_core.ipynb",
         "input_vals": "00_core.ipynb",
         "foo_f": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://choct155.github.io/nbdev_test/"

git_url = "https://github.com/choct155/nbdev_test/tree/master/"

def custom_doc_links(name): return None
